// auth
export const SET_USER = 'SET_USER'
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_TOKEN = 'SET_TOKEN'
// counts
export const SET_COUNTS = 'SET_COUNTS'
export const SET_USERCOUNTS = 'SET_USERCOUNTS'
export const RESET_COUNTS = 'RESET_COUNTS'
export const RESET_USERCOUNTS = 'RESET_USERCOUNTS'
// boxes
export const SET_BOXES = 'SET_BOXES'
export const RESET_BOXES = 'RESET_BOXES'
// nendoroids
export const SET_NENDOROIDS = 'SET_NENDOROIDS'
export const RESET_NENDOROIDS = 'RESET_NENDOROIDS'
// faces
export const SET_FACES = 'SET_FACES'
export const RESET_FACES = 'RESET_FACES'
// hairs
export const SET_HAIRS = 'SET_HAIRS'
export const RESET_HAIRS = 'RESET_HAIRS'
// hands
export const SET_HANDS = 'SET_HANDS'
export const RESET_HANDS = 'RESET_HANDS'
// bodyparts
export const SET_BODYPARTS = 'SET_BODYPARTS'
export const RESET_BODYPARTS = 'RESET_BODYPARTS'
// accessories
export const SET_ACCESSORIES = 'SET_ACCESSORIES'
export const RESET_ACCESSORIES = 'RESET_ACCESSORIES'
// photos
export const SET_PHOTOS = 'SET_PHOTOS'
export const RESET_PHOTOS = 'RESET_PHOTOS'
export const SET_PHOTOACCESSORIES = 'SET_PHOTOACCESSORIES'
export const RESET_PHOTOACCESSORIES = 'RESET_PHOTOACCESSORIES'
export const SET_PHOTOBODYPARTS = 'SET_PHOTOBODYPARTS'
export const RESET_PHOTOBODYPARTS = 'RESET_PHOTOBODYPARTS'
export const SET_PHOTOBOXES = 'SET_PHOTOBOXES'
export const RESET_PHOTOBOXES = 'RESET_PHOTOBOXES'
export const SET_PHOTOFACES = 'SET_PHOTOFACES'
export const RESET_PHOTOFACES = 'RESET_PHOTOFACES'
export const SET_PHOTOHAIRS = 'SET_PHOTOHAIRS'
export const RESET_PHOTOHAIRS = 'RESET_PHOTOHAIRS'
export const SET_PHOTOHANDS = 'SET_PHOTOHANDS'
export const RESET_PHOTOHANDS = 'RESET_PHOTOHANDS'
export const SET_PHOTONENDOROIDS = 'SET_PHOTONENDOROIDS'
export const RESET_PHOTONENDOROIDS = 'RESET_PHOTONENDOROIDS'
